version: "3.8"
services:
  backend:
    container_name: backend
    image: app-backend
    networks:
      - app-network
    volumes:
    - /home/srinibasmisra/docker-demos/backend:/app
  frontend:
    container_name: frontend
    image: app-frontend:1
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
    - /home/srinibasmisra/docker-demos/frontend:/usr/share/nginx/html
    depends_on:
      - backend
networks:
  app-network:
    driver: bridge